### ISSUE TITLE
Getting started with a working example

### ISSUE THREAD

**Issue by NRaoV** [englishtown/vertx-jersey#28] opened 2015-02-12 02:33 UTC
Hi All,

Thanks for latest updates in this project. Started exploring the project by running example.

Need your help on the following

- Examples are not running without vertx-maven-plugin. Getting the errors even after adding plugin at parent pom for examples.

[INFO] --- vertx-maven-plugin:2.0.11-final:runMod (default-cli) @ vertx-jersey-e
xamples-jackson ---
Feb 12, 2015 7:49:40 AM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.vertx.maven.plugin.mojo.VertxRunModMojo
java.lang.NoClassDefFoundError: org/vertx/java/core/Handler
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
        at java.lang.Class.getDeclaredConstructors(Class.java:2007)
        at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.
java:245)

Any insights or working example would help.

**Comment by adrianluisgonzalez** [comment] 2015-03-18 22:53
What version are you trying to run?  The develop branch is based on vert.x3 which does not use the vertx-maven-plugin.

**Comment by okiim** [comment] 2015-03-20 09:43
Hi,
apologises, I'm quite new in vertex, perhaps it's just lack of experience but the problem is I cant run an example with injection (inject-vertx),- it was compiled, built but it is not possible to run it.

**Comment by adrianluisgonzalez** [comment] 2015-03-20 21:50
Vert.x 3.0.0-milestone3 had some breaking changes that are not compatible with vertx-jersey 4.0.0-RC1.  I released a new version 4.0.0-RC2 yesterday and added some integration tests.  Can you try that?
https://github.com/englishtown/vertx-jersey/tree/4.0.0-RC2

Also, there is now a runnable integration test for inject-vertx:
https://github.com/englishtown/vertx-jersey/blob/develop/examples/inject-vertx/src/test/java/com/englishtown/vertx/jersey/examples/integration/InjectionIntegrationTest.java

Unfortunately the documentation is still not up to date, that's something I will be working over the coming days.

**Comment by okiim** [comment] 2015-03-23 13:28
Hi Adrian,
thank you indeed! Now it works fine! 
It's amazing how quickly you coped with this!
Thanks!

**Comment by adrianluisgonzalez** [comment] 2015-03-23 13:32
Glad it's working.  I'll close this issue.

**Closed by adrianluisgonzalez** 2015-03-23 13:32 UTC

**Comment by NRaoV** [comment] 2015-03-24 05:06
Thanks it is working!!!

**Comment by NRaoV** [comment] 2015-03-24 11:34
Hi, I am happy to share a bootstrap sort of application using verx-jersey.

https://github.com/NRaoV/vertx-jersey-webapp

Happy to share at the core module. I found it is very useful for all the developer who just kick-start writing REST application using vertex-jersey.

**Comment by NRaoV** [comment] 2015-03-24 11:40
Hi All,


I have written a small getting started example which works perfectly. You
can download and use the code from

https://github.com/NRaoV/vertx-jersey-webapp

All points like, Commad-line parser for validating arguments, configuration
manager to manage app wide properties, assembly-plugin for build and
finally script files to launch verticle.

All you need is to just enhance/write your service and drop then in
"resource" package to get it auto deployed.

Thanks,
Nageswara Rao



On Mon, Mar 23, 2015 at 7:02 PM, Adrian <notifications@github.com> wrote:

> Glad it's working. I'll close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/englishtown/vertx-jersey/issues/28#issuecomment-84998212>
> .
>



-- 
Thanks,
Nageswara Rao.V

*"The LORD reigns"*

**Comment by adrianluisgonzalez** [comment] 2015-03-24 17:32
Thanks for the vertx-jersey-webapp starter app, the more help the better! 

A few comments about pom.xml

* Looks like you're missing a dependency to org.slf4j in your pom, I got a compilation error.
* With vert.x 3.0.0-milestone3, I would recommend using vertx-jersey 4.0.0-RC2 and vertx-hk2 2.0.0-RC2
* The JUnit dependency should probably have `<scope>test</scope>`
* It looks like the gson dependency is not used and can be removed.
* My understanding is platform_lib has no meaning in vert.x 3, I think that can be removed.

You might want to add the following:
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-dependencies</artifactId>
                <version>${vertx.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```


I noticed you're running vert.x as an embedded application in your `Runner` class.  In vert.x 2.x that was considered a more advanced approach, perhaps that has changed in vert.x 3.  Running a fat jar might be the easiest way to get started using the maven shade plugin.

**Comment by NRaoV** [comment] 2015-03-25 10:44
Thanks for the review, Fixed.

Build works fine locally.

Please have a look.

On Tue, Mar 24, 2015 at 11:02 PM, Adrian <notifications@github.com> wrote:

> Thanks for the vertx-jersey-webapp starter app, the more help the better!
>
> A few comments about pom.xml
>
>    - Looks like you're missing a dependency to org.slf4j in your pom, I
>    got a compilation error.
>    - With vert.x 3.0.0-milestone3, I would recommend using vertx-jersey
>    4.0.0-RC2 and vertx-hk2 2.0.0-RC2
>    - The JUnit dependency should probably have <scope>test</scope>
>    - It looks like the gson dependency is not used and can be removed.
>    - My understanding is platform_lib has no meaning in vert.x 3, I think
>    that can be removed.
>
> You might want to add the following:
>
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>io.vertx</groupId>
>                 <artifactId>vertx-dependencies</artifactId>
>                 <version>${vertx.version}</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>
> I noticed you're running vert.x as an embedded application in your Runner
> class. In vert.x 2.x that was considered a more advanced approach, perhaps
> that has changed in vert.x 3. Running a fat jar might be the easiest way to
> get started using the maven shade plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/englishtown/vertx-jersey/issues/28#issuecomment-85610282>
> .
>



-- 
Thanks,
Nageswara Rao.V

*"The LORD reigns"*
